/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "suma.h"
#include <stdio.h>

void suma_prog_1(char *host, int numero1, int numero2)
{
	CLIENT *clnt;
	int *result_1;
	dupla_int suma_1_arg;

	suma_1_arg.a = numero1;
	suma_1_arg.b = numero2;

#ifndef DEBUG
	clnt = clnt_create(host, SUMA_PROG, SUMA_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	result_1 = suma_1(&suma_1_arg, clnt);
	if (result_1 == (int *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Resultado SUMA (numero1+numero2): %d\n", *result_1);
	}
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;
	int numero1, numero2;

	if (argc != 4)
	{
		printf("Uso: %s server_host numero1 numero2\n", argv[0]);
		exit(1);
	}

	host = argv[1];
	numero1 = atoi(argv[2]);
	numero2 = atoi(argv[3]);
	if (numero1 == 0 && *argv[2] != '0')
	{
		fprintf(stderr, "Valor no valido: %s\n", argv[2]);
		exit(1);
	}
	else if (numero2 == 0 && *argv[3] != '0')
	{
		fprintf(stderr, "Valor no valido: %s\n", argv[3]);
		exit(1);
	}
	suma_prog_1(host, numero1, numero2);
	exit(0);
}
