/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "suma.h"

int *
suma_1_svc(dupla_int *argp, struct svc_req *rqstp)
{
	static int  result;
	result = argp->a + argp->b;
	printf("El procedimiento SUMA ha sido invocado remotamente (numero1+numero2): %d\n",result);
	return &result;
}
