/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

float *
suma_1_svc(dupla_int *argp, struct svc_req *rqstp)
{
	static float result;
	result = (float)argp->a + (float)argp->b;
	printf("El procedimiento SUMA ha sido invocado remotamente (numero1+numero2): %f\n",result);
	return &result;
}

float *
resta_1_svc(dupla_int *argp, struct svc_req *rqstp)
{
	static float result;
	result = (float)argp->a - (float)argp->b;
	printf("El procedimiento RESTA ha sido invocado remotamente (numero1-numero2): %f\n",result);
	return &result;
}

float *
multiplicacion_1_svc(dupla_int *argp, struct svc_req *rqstp)
{
	static float result;
	result = (float)argp->a * (float)argp->b;
	printf("El procedimiento MULTIPLICACION ha sido invocado remotamente (numero1*numero2): %f\n",result);
	return &result;
}

float *
division_1_svc(dupla_int *argp, struct svc_req *rqstp)
{
	static float result;
	result = (float)argp->a / (float)argp->b;
	printf("El procedimiento DIVISION ha sido invocado remotamente (numero1/numero2): %f\n\n",result);
	return &result;
}
