/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

void calculadora_prog_1(char *host, int numero1, int numero2)
{
	CLIENT *clnt;
	float *result_1;
	dupla_int suma_1_arg;
	float *result_2;
	dupla_int resta_1_arg;
	float *result_3;
	dupla_int multiplicacion_1_arg;
	float *result_4;
	dupla_int division_1_arg;

	suma_1_arg.a = numero1;
	suma_1_arg.b = numero2;

	resta_1_arg.a = numero1;
	resta_1_arg.b = numero2;

	multiplicacion_1_arg.a = numero1;
	multiplicacion_1_arg.b = numero2;

	division_1_arg.a = numero1;
	division_1_arg.b = numero2;

#ifndef DEBUG
	clnt = clnt_create(host, CALCULADORA_PROG, CALCULADORA_VERS, "udp");
	if (clnt == NULL)
	{
		clnt_pcreateerror(host);
		exit(1);
	}
#endif /* DEBUG */

	result_1 = suma_1(&suma_1_arg, clnt);
	if (result_1 == (float *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Resultado SUMA (numero1+numero2): %f\n", *result_1);
	}

	result_2 = resta_1(&resta_1_arg, clnt);
	if (result_2 == (float *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Resultado RESTA (numero1-numero2): %f\n", *result_2);
	}

	result_3 = multiplicacion_1(&multiplicacion_1_arg, clnt);
	if (result_3 == (float *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Resultado MULTIPLICACION (numero1*numero2): %f\n", *result_3);
	}

	result_4 = division_1(&division_1_arg, clnt);
	if (result_4 == (float *)NULL)
	{
		clnt_perror(clnt, "call failed");
	}
	else
	{
		printf("Resultado DIVISION (numero1/numero2): %f\n",*result_4);
	}
#ifndef DEBUG
	clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[])
{
	char *host;
	int numero1, numero2;

	if (argc != 4)
	{
		printf("Uso: %s server_host numero1 numero2\n", argv[0]);
		exit(1);
	}

	host = argv[1];
	numero1 = (long)atoi(argv[2]);
	numero2 = atoi(argv[3]);
	calculadora_prog_1(host, numero1, numero2);
	exit(0);
}
