/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */
#include "rand.h"

void *
inicializa_random_1_svc(long *argp, struct svc_req *rqstp)
{
	static char * result;

	srandom(*argp);

	return (void *) &result;
}

int *
obtiene_siguiente_random_1_svc(void *argp, struct svc_req *rqstp)
{
	static int  result;

	result=random();

	printf("El procedimiento para generar numeros aleatorios ha sido invocado remotamente: %d\n",result);

	return &result;
}
